// Generated by gencpp from file hand_roscv/control_srv.msg
// DO NOT EDIT!


#ifndef HAND_ROSCV_MESSAGE_CONTROL_SRV_H
#define HAND_ROSCV_MESSAGE_CONTROL_SRV_H

#include <ros/service_traits.h>


#include <hand_roscv/control_srvRequest.h>
#include <hand_roscv/control_srvResponse.h>


namespace hand_roscv
{

struct control_srv
{

typedef control_srvRequest Request;
typedef control_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct control_srv
} // namespace hand_roscv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hand_roscv::control_srv > {
  static const char* value()
  {
    return "983bd86bd8f878d29cc8c58c940fb25f";
  }

  static const char* value(const ::hand_roscv::control_srv&) { return value(); }
};

template<>
struct DataType< ::hand_roscv::control_srv > {
  static const char* value()
  {
    return "hand_roscv/control_srv";
  }

  static const char* value(const ::hand_roscv::control_srv&) { return value(); }
};


// service_traits::MD5Sum< ::hand_roscv::control_srvRequest> should match
// service_traits::MD5Sum< ::hand_roscv::control_srv >
template<>
struct MD5Sum< ::hand_roscv::control_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hand_roscv::control_srv >::value();
  }
  static const char* value(const ::hand_roscv::control_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_roscv::control_srvRequest> should match
// service_traits::DataType< ::hand_roscv::control_srv >
template<>
struct DataType< ::hand_roscv::control_srvRequest>
{
  static const char* value()
  {
    return DataType< ::hand_roscv::control_srv >::value();
  }
  static const char* value(const ::hand_roscv::control_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hand_roscv::control_srvResponse> should match
// service_traits::MD5Sum< ::hand_roscv::control_srv >
template<>
struct MD5Sum< ::hand_roscv::control_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hand_roscv::control_srv >::value();
  }
  static const char* value(const ::hand_roscv::control_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hand_roscv::control_srvResponse> should match
// service_traits::DataType< ::hand_roscv::control_srv >
template<>
struct DataType< ::hand_roscv::control_srvResponse>
{
  static const char* value()
  {
    return DataType< ::hand_roscv::control_srv >::value();
  }
  static const char* value(const ::hand_roscv::control_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAND_ROSCV_MESSAGE_CONTROL_SRV_H
