// Generated by gencpp from file panda_arm_control/effector_control_param.msg
// DO NOT EDIT!


#ifndef PANDA_ARM_CONTROL_MESSAGE_EFFECTOR_CONTROL_PARAM_H
#define PANDA_ARM_CONTROL_MESSAGE_EFFECTOR_CONTROL_PARAM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <trajectory_msgs/JointTrajectory.h>

namespace panda_arm_control
{
template <class ContainerAllocator>
struct effector_control_param_
{
  typedef effector_control_param_<ContainerAllocator> Type;

  effector_control_param_()
    : work_mode()
    , supplement()
    , x0(0.0)
    , y0(0.0)
    , z0(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , w(0.0)
    , traj()  {
    }
  effector_control_param_(const ContainerAllocator& _alloc)
    : work_mode(_alloc)
    , supplement(_alloc)
    , x0(0.0)
    , y0(0.0)
    , z0(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , w(0.0)
    , traj(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _work_mode_type;
  _work_mode_type work_mode;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _supplement_type;
  _supplement_type supplement;

   typedef float _x0_type;
  _x0_type x0;

   typedef float _y0_type;
  _y0_type y0;

   typedef float _z0_type;
  _z0_type z0;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _w_type;
  _w_type w;

   typedef  ::trajectory_msgs::JointTrajectory_<ContainerAllocator>  _traj_type;
  _traj_type traj;





  typedef boost::shared_ptr< ::panda_arm_control::effector_control_param_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_arm_control::effector_control_param_<ContainerAllocator> const> ConstPtr;

}; // struct effector_control_param_

typedef ::panda_arm_control::effector_control_param_<std::allocator<void> > effector_control_param;

typedef boost::shared_ptr< ::panda_arm_control::effector_control_param > effector_control_paramPtr;
typedef boost::shared_ptr< ::panda_arm_control::effector_control_param const> effector_control_paramConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_arm_control::effector_control_param_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_arm_control::effector_control_param_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_arm_control::effector_control_param_<ContainerAllocator1> & lhs, const ::panda_arm_control::effector_control_param_<ContainerAllocator2> & rhs)
{
  return lhs.work_mode == rhs.work_mode &&
    lhs.supplement == rhs.supplement &&
    lhs.x0 == rhs.x0 &&
    lhs.y0 == rhs.y0 &&
    lhs.z0 == rhs.z0 &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.w == rhs.w &&
    lhs.traj == rhs.traj;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_arm_control::effector_control_param_<ContainerAllocator1> & lhs, const ::panda_arm_control::effector_control_param_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_arm_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panda_arm_control::effector_control_param_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_arm_control::effector_control_param_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_arm_control::effector_control_param_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_arm_control::effector_control_param_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_arm_control::effector_control_param_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_arm_control::effector_control_param_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_arm_control::effector_control_param_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5215bcd504493e63651b35034e0fe1c3";
  }

  static const char* value(const ::panda_arm_control::effector_control_param_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5215bcd504493e63ULL;
  static const uint64_t static_value2 = 0x651b35034e0fe1c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_arm_control::effector_control_param_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_arm_control/effector_control_param";
  }

  static const char* value(const ::panda_arm_control::effector_control_param_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_arm_control::effector_control_param_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string work_mode\n"
"string supplement\n"
"float32 x0\n"
"float32 y0\n"
"float32 z0\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 w\n"
"trajectory_msgs/JointTrajectory traj\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectory\n"
"Header header\n"
"string[] joint_names\n"
"JointTrajectoryPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectoryPoint\n"
"# Each trajectory point specifies either positions[, velocities[, accelerations]]\n"
"# or positions[, effort] for the trajectory to be executed.\n"
"# All specified values are in the same order as the joint names in JointTrajectory.msg\n"
"\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] accelerations\n"
"float64[] effort\n"
"duration time_from_start\n"
;
  }

  static const char* value(const ::panda_arm_control::effector_control_param_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_arm_control::effector_control_param_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.work_mode);
      stream.next(m.supplement);
      stream.next(m.x0);
      stream.next(m.y0);
      stream.next(m.z0);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.w);
      stream.next(m.traj);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct effector_control_param_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_arm_control::effector_control_param_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_arm_control::effector_control_param_<ContainerAllocator>& v)
  {
    s << indent << "work_mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.work_mode);
    s << indent << "supplement: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.supplement);
    s << indent << "x0: ";
    Printer<float>::stream(s, indent + "  ", v.x0);
    s << indent << "y0: ";
    Printer<float>::stream(s, indent + "  ", v.y0);
    s << indent << "z0: ";
    Printer<float>::stream(s, indent + "  ", v.z0);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
    s << indent << "traj: ";
    s << std::endl;
    Printer< ::trajectory_msgs::JointTrajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.traj);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_ARM_CONTROL_MESSAGE_EFFECTOR_CONTROL_PARAM_H
